web:
  image: reload/drupal-apache-ssl
  ports:
    - '80/tcp'
    - '443/tcp'
  volumes:
    - './web:/var/www/html'
    - './docker/settings.php:/var/www/html/sites/default/settings.php:ro'
    - './docker/drupal-cron.conf:/etc/cron.d/drupal-cron.conf:ro'
    - './docker/prepare-environment.sh:/etc/my_init.d/prepare-environment.sh'
    - './docker/php.ini:/etc/php/5.6/mods-available/ding.ini'
  links:
    - db
    - memcached
  environment:
    PHP_EXTRA_EXTENSIONS: memcached
  working_dir: /var/www/html
db:
  image: mariadb
  ports:
    - '3306/tcp'
  environment:
    MYSQL_ROOT_PASSWORD: Iec4aiphies7ohFa5fo5koh3aisaew
    MYSQL_DATABASE: db
    MYSQL_USER: db
    MYSQL_PASSWORD: ichai4IesaeSainohV0oT2ca9hooNi
gulp:
  image: node:argon
  volumes:
    - './web/profiles/ding2/themes/ddbasic:/src'
  entrypoint: "/bin/sh -c 'cd /src && npm install --unsafe-perm && node_modules/.bin/gulp sass'"
drush:
  image: drush/drush
  links:
    - db
  volumes_from:
    - web
  working_dir: /var/www/html
memcached:
  image: memcached
varnish:
  image: zenedith/varnish
  environment:
    VCL_FILE: /opt/ding2.vcl
    LISTEN_PORT: 80
  volumes:
    - './web/profiles/ding2/ding2.vcl:/opt/ding2.vcl'
  ports:
    - '80/tcp'
  links:
    - web
